using UnityEngine;
using UnityEngine.SceneManagement;


public class Music : MonoBehaviour
{
    public static Music instance;


    void Awake()
    {
        if (instance == null)
        {
            // if instance is null, store a reference to this instance
            instance = this;
            DontDestroyOnLoad(gameObject);
            print("dont destroy");
        }
        else
        {
            // Another instance of this gameobject has been made so destroy it
            // as we already have one
            print("do destroy");
            Destroy(gameObject);
        }

        Scene scene = SceneManager.GetActiveScene();
        if(scene != null)
        {
            if(scene.name == "OutOfBounds")
            {
                Destroy(gameObject);
            }
        }
    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
